-- Synthetic users only; all test data is rolled back. No existing documents read.
begin;
do $$
declare a uuid := gen_random_uuid(); b uuid := gen_random_uuid(); c uuid := gen_random_uuid(); v jsonb;
  sale_id bigint; position_id bigint; stock_id bigint; result jsonb; receipt uuid := gen_random_uuid(); denied boolean;
begin
  insert into auth.users(id) values(a),(b),(c);
  perform set_config('request.jwt.claim.sub',a::text,true);
  execute 'set local role authenticated';
  v := '[{"id":"check-stock","displayName":"synthetic","positions":[{"id":1,"number":1,"buyPrice":10,"buyQty":5,"trades":[{"id":10,"type":"SELL","qty":2,"price":20}]}]}]';
  perform public.silver_write_document('portfolioStocks',v,0,gen_random_uuid());
  v := jsonb_set(v,'{0,positions,0,trades}','[]');
  perform public.silver_write_document('portfolioStocks',v,1,gen_random_uuid());
  select id into sale_id from public.silver_trash where kind = 'trade';
  if sale_id is null then raise exception 'Sale not captured'; end if;
  v := jsonb_set(v,'{0,positions}','[]');
  perform public.silver_write_document('portfolioStocks',v,2,gen_random_uuid());
  select id into position_id from public.silver_trash where kind = 'position';
  perform public.silver_write_document('portfolioStocks','[]',3,gen_random_uuid());
  select id into stock_id from public.silver_trash where kind = 'stock';
  if jsonb_array_length(public.silver_list_trash()) <> 3 then raise exception 'Parent delete should capture one complete item'; end if;
  denied := false;
  begin perform public.silver_trash_action(sale_id,'restore',gen_random_uuid(),a);
  exception when raise_exception then denied := true; end;
  if not denied then raise exception 'Missing parent restoration accepted'; end if;
  perform public.silver_trash_action(stock_id,'restore',gen_random_uuid(),a);
  perform public.silver_trash_action(position_id,'restore',gen_random_uuid(),a);
  result := public.silver_trash_action(sale_id,'restore',receipt,a);
  if result->'document'->'value'->0->'positions'->0->>'remainQty' is distinct from '3'
    or result->'document'->'value'->0->'positions'->0->>'realizedPnL' is distinct from '20' then raise exception 'Restored totals incorrect'; end if;
  if result is distinct from public.silver_trash_action(sale_id,'restore',receipt,a) then raise exception 'Trash retry duplicated'; end if;
  if exists(select 1 from public.silver_read_changes('{"portfolioStocks":7}')) then raise exception 'Unchanged document resent'; end if;
  if (select count(*) from public.silver_read_changes('{"portfolioStocks":6}')) <> 1 then raise exception 'Changed document missing'; end if;
  perform public.silver_write_document('stockHistory','[{"id":1,"price":10,"pct":1},{"id":2,"price":20,"pct":2}]',0,gen_random_uuid());
  perform public.silver_write_document('stockHistory','[]',1,gen_random_uuid());
  if (select count(*) from public.silver_trash where kind = 'history') <> 1 then raise exception 'Bulk history removal not grouped'; end if;
  select id into stock_id from public.silver_trash where kind = 'history';
  perform public.silver_trash_action(stock_id,'restore',gen_random_uuid(),a);
  if jsonb_array_length(public.silver_read_document('stockHistory')->'value') <> 2 then raise exception 'History not restored'; end if;
  perform public.silver_write_document('portfolioStocks','[]',7,gen_random_uuid());
  select id into stock_id from public.silver_trash where kind = 'stock';
  perform public.silver_write_document('portfolioStocks','[{"id":"check-stock","positions":[]}]',8,gen_random_uuid());
  denied := false;
  begin perform public.silver_trash_action(stock_id,'restore',gen_random_uuid(),a);
  exception when raise_exception then denied := true; end;
  if not denied or not exists(select 1 from public.silver_trash where id = stock_id) then raise exception 'Duplicate restore overwrote or lost backup'; end if;
  denied := false;
  begin delete from public.silver_trash where owner_id = a;
  exception when insufficient_privilege then denied := true; end;
  if not denied then raise exception 'Direct trash deletion allowed'; end if;
  perform set_config('request.jwt.claim.sub',b::text,true);
  if public.silver_list_trash() <> '[]'::jsonb then raise exception 'Other account trash visible'; end if;
  denied := false;
  begin perform public.silver_trash_action(stock_id,'delete',gen_random_uuid(),a);
  exception when insufficient_privilege then denied := true; end;
  if not denied then raise exception 'Wrong owner accepted'; end if;
  perform set_config('request.jwt.claim.sub',c::text,true);
  v := '[{"id":"oversale","positions":[{"id":1,"buyPrice":10,"buyQty":5,"trades":[{"id":1,"type":"SELL","qty":2,"price":20}]}]}]';
  perform public.silver_write_document('portfolioStocks',v,0,gen_random_uuid());
  v := jsonb_set(jsonb_set(v,'{0,positions,0,trades}','[]'),'{0,positions,0,buyQty}','1');
  perform public.silver_write_document('portfolioStocks',v,1,gen_random_uuid());
  select id into sale_id from public.silver_trash where kind = 'trade';
  denied := false;
  begin perform public.silver_trash_action(sale_id,'restore',gen_random_uuid(),c);
  exception when raise_exception then denied := true; end;
  if not denied or not exists(select 1 from public.silver_trash where id = sale_id)
    or public.silver_read_document('portfolioStocks')->>'version' <> '2' then raise exception 'Oversale restore changed or lost data'; end if;
  perform set_config('request.jwt.claim.sub',b::text,true);
  perform public.silver_write_document('portfolioStocks','[{"id":"capacity","positions":[]}]',0,gen_random_uuid());
  execute 'reset role';
  insert into public.silver_trash(owner_id,kind,label,payload)
    select b,'stock','synthetic capacity',jsonb_build_object('item',jsonb_build_object('id',n::text,'positions','[]'::jsonb)) from generate_series(1,200) n;
  execute 'set local role authenticated';
  denied := false;
  begin perform public.silver_write_document('portfolioStocks','[]',1,gen_random_uuid());
  exception when raise_exception then denied := true; end;
  if not denied or jsonb_array_length(public.silver_read_document('portfolioStocks')->'value') <> 1 then raise exception 'Full trash lost active document'; end if;
  perform public.silver_trash_action(null,'empty',gen_random_uuid(),b);
  if public.silver_list_trash() <> '[]'::jsonb then raise exception 'Empty trash failed'; end if;
  execute 'reset role';
  execute 'set local role anon';
  denied := false;
  begin perform public.silver_list_trash(); exception when insufficient_privilege then denied := true; end;
  if not denied then raise exception 'Anonymous trash access allowed'; end if;
  execute 'reset role';
end $$;
rollback;
select 'PASS: atomic trash capture, parent restore, totals, duplicate protection, retry, isolation, capacity rollback, history, compact changes; fixtures rolled back' as deployment_check;
